language: ruby
rvm:
- 2.1.2
before_install:
- npm install -g grunt-cli
install:
- bundle install
- gem install rb-gsl
- npm install
before_script:
- cp grunt-aws.example.json grunt-aws.json
script: grunt build
branches:
  only:
  - master
