env: 'production'
destination: '.tmp'
url: "http://blog.cartodb.com"

cartodb-baseurl: 'http://cartodb.com'
docs-baseurl: 'http://docs.cartodb.com'
docs-baseurl: 'http://docs.cartodb.com'

analytics_property_id: 'UA-20934186-3'
mixpanel_token: '9b1d8a4fb14fa98d50615108b8b0161a'
mailchimp_id: '88c00b7e33'
tech_newsletter: 'b85d5d7d87'
