# Site settings
title: CartoDB | Blog
email: your-email@domain.com
description: "We love Open Data. CartoDB is a geospatial database on the cloud to allow development of location aware applications quickly and easily."
keywords: "cartodb, map of the week, nonprofits, cartodb partners, examples"
baseurl: ""
url: "http://blog.cartodb.com/"

# Build settings
markdown: kramdown
permalink: pretty
encoding: utf-8
exclude: ['README.md']
gems:
  - jekyll-compass
